name = "fortplot_user_template"
version = "0.1.0"
license = "MIT"
author = "Your Name"
maintainer = "your.email@domain.com"

[fortran]
implicit-typing = false

[dependencies]
fortplot = { git = "https://github.com/lazy-fortran/fortplot" }

[[executable]]
name = "fpm_template_demo"
source-dir = "app"
main = "fpm_template_demo.f90"